### ISSUE TITLE
Create a new GitHub organization for this repository

### ISSUE THREAD

**Issue by diversenok** [sandboxie-dev/Sandboxie#2]
Greetings, @DavidXanatos

I think we can create a new GitHub organization for keeping Sandboxie's code and accumulating its further development. I see this repository starts gaining attention, so I was wondering if you want to do so. It will help to bring the community in one place and continue improving this product collaboratively on GitHub.

I would love to participate, and I hope we can find more people with sufficient skills and motivation to improve this program together. And making a GitHub organization seems like a reasonable first step.

**Comment by mrkaban** [comment]
When adding ~ 1600 people a day to a site with traffic ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D1%8C/%D0%B0%D0%BD%D1%82%D0%B8%D0%B2%D0%B8%D1%80%D1%83%D1%81%D1%8B/sandboxie-%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0.html)), he indicated a link to this repository! Thank you for posting here, otherwise it is difficult to download from the official site!

Let's hope for active development!

**Comment by DavidXanatos** [comment]
Like that: https://github.com/xanasoft/Sandboxie

**Comment by diversenok** [comment]
Yes, pretty much. I know, it's just a rule of thumb, but I think people tend to see personal repositories as personal projects, and organizational repositories as a place for community-driven development. This approach might be beneficial in the long-term if we want to accumulate all improvements in one place.

Now you can assign yourself as public a member, and later do the same with other contributors.

**Comment by DavidXanatos** [comment]
Ok done, now I'm public.
mmh.. by this rational I probably should move TaskExplorer, DiskCryptor and priv10, wumgr also to an organization... as these are project for he public and not just for my personal enjoyment.

**Comment by diversenok** [comment]
I guess the final decision depends on whether you expect anyone else to participate in their development or not. By personal projects, I mostly mean repositories that only you will contribute to, without regard to minor changes proposed via pull requests. It doesn't mean that they are uninteresting to the public at large; it's more about how the process of improvement involves the community.

**Comment by DavidXanatos** [comment]
I have reorganized a bit, 
now we have https://github.com/sandbox-ie/Sandboxie
unfortunately github.com/sandboxie was already taken since January
but sandbox-ie is also good I think or would sandboxxy be better?

**Comment by mrkaban** [comment]
I think it would be better to "sandboxie-dev" and no longer change url!

**Comment by zhudock** [comment]
I'd vote for "sandboxie-dev", unless you really want to start to diverge from the original project. In that case, "sandboxxy"

**Comment by DavidXanatos** [comment]
sandboxie-dev it is than

**Comment by matheuswillder** [comment]
Apparently the Source Code released by Sophos was also recently placed in the mentioned repository (github.com/sandboxie).

Regarding the repository/organization name, I really think it will be a creative and personal choice for everyone who wants to go ahead with the project and also for the forks from them, certainly the Sandboxie offers many other personalities.

I'm not a developer, but I'll keep an eye out for what comes up from now on. Maybe someday I can help in some way.

**Comment by burnsjackie** [comment]
Agreed this one should be abandoned, real Sandboxie is here https://github.com/sandboxie-plus/Sandboxie/issues?q=is%3Aissue+is%3Aclosed

This one is signed with a malware signer...

**Comment by mrkaban** [comment]
I ask you very strongly not to change the name! I was tortured every day to change the URL on the site.

**Comment by DavidXanatos** [comment]
I wanted to avoid name confusion, with the other mentioned repo. Sorry for the extra work.
Github is auto redirecting in such cases anyways so if you would have left the old url it would still work.
